"""A file that contains functions that apply data augmentations.

1. `extract_random_patches`: Extracts random patches from an image.
"""
import numpy as np


def extract_random_patches(img, patch_size=20, num_patches=5, radius_percentage=0.5):
    """
    Extracts random patches from an image.
    img        : H×W or H×W×C  NumPy array
    patch_size : int           size of the patches to extract
    num_patches: int           number of patches to extract
    radius_percentage     : float         radius_percentage of the the image of the circle from which to sample the patches
    
    """
    h, w = img.shape[:2]
    cx, cy = w // 2, h // 2
    r =  radius_percentage * h  //2 # radius for sampling

    patches = []
    for _ in range(num_patches):
        while True:
            dx = np.random.randint(-r, r)
            dy = np.random.randint(-r, r)
            if dx**2 + dy**2 <= r**2:
                x = cx + dx - patch_size // 2
                y = cy + dy - patch_size // 2
                if 0 <= x < w - patch_size and 0 <= y < h - patch_size:
                    patch = img[y:y+patch_size, x:x+patch_size]
                    patches.append(patch)
                    break
    return patches



def random_flip_rotate_np(img, rng=None):
    """
    img  : H×W or H×W×C  NumPy array
    rng  : np.random.Generator (optional)
    • 50 % chance horizontal flip
    • 50 % chance vertical flip
    • random 0/90/180/270° rotation
    """
    rng = rng or np.random.default_rng()
    if rng.random() < 0.5:          # H-flip
        img = np.flip(img, axis=1)
    if rng.random() < 0.5:          # V-flip
        img = np.flip(img, axis=0)
    k = rng.integers(0, 4)          # rotate k×90°
    img = np.rot90(img, k, axes=(0, 1))
    return img.copy()               # ensure contiguous memory



if __name__ == "__main__":
    # We will apply the data augmentation to the images generated by Algoritme A and Algoritme B

    # Load the images
    images_A = np.load('data/full_images_algoA.npy', allow_pickle=True)
    images_B = np.load('data/full_images_algoB.npy', allow_pickle=True)

    # Number of augmented images per original image
    num_augmented = 5

    augmented_A = []
    augmented_B = []

    patch_size = 50

    for img in images_A:
        for _ in range(num_augmented):
            aug_img = random_flip_rotate_np(img[0,0,:,:])
            patches = extract_random_patches(aug_img, patch_size=patch_size, num_patches=20, radius_percentage=0.8)
            augmented_A.extend(patches)  # Save all patches

    for img in images_B:
        for _ in range(num_augmented):
            aug_img = random_flip_rotate_np(img[0,0,:,:])
            patches = extract_random_patches(aug_img, patch_size=patch_size, num_patches=20, radius_percentage=0.8)
            augmented_B.extend(patches)  # Save all patches

    augmented_A = np.array(augmented_A)
    augmented_B = np.array(augmented_B)

    np.save('data/augmented_images_algoA.npy', augmented_A)
    np.save('data/augmented_images_algoB.npy', augmented_B)


